macro(setup_log)
  if (LOG_ON)
    add_compile_definitions("LOG_ON")
    module_message("LOG_ON is defined")
  else()
    module_message("LOG_ON is not defined")
  endif ()
  if (LOG_LEVEL_VERBOSE)
    add_compile_definitions("LOG_LEVEL_VERBOSE")
    module_message("LOG_LEVEL_VERBOSE is defined")
  else()
    module_message("LOG_LEVEL_VERBOSE is not defined")
  endif ()
  if (LOG_LEVEL_DEBUG)
    add_compile_definitions("LOG_LEVEL_DEBUG")
    module_message("LOG_LEVEL_DEBUG is defined")
  else()
    module_message("LOG_LEVEL_DEBUG is not defined")
  endif()
endmacro(setup_log)
