macro(setup_qt_dir)
	if("${QT_DIR}" STREQUAL "")
		set(QT_DIR $ENV{QT_DIR})
	endif()
	if("${QT_DIR}" STREQUAL "")
		message(WARNING "${PROJECT_NAME}: setup_qt_dir: WARNING: QT_DIR is not specified")
	endif()
endmacro(setup_qt_dir)

macro(setup_qt_cmake_prefix_path)
	if ("${CMAKE_PREFIX_PATH}" STREQUAL "")
		setup_qt_dir()
		setup_generator_short_name()
		set(CMAKE_PREFIX_PATH ${QT_DIR}/${GENERATOR_SHORT_NAME})
	endif()
endmacro(setup_qt_cmake_prefix_path)
