macro(setup_inherit_parent)
	option(INHERIT_PARENT_SRC "Adds all parent's source files" OFF)
	option(INHERIT_PARENT_LIBS "Adds all parent's libraries" OFF)
	message("${MODULE_NAME}: INHERIT_PARENT_SRC is ${INHERIT_PARENT_SRC}")
	message("${MODULE_NAME}: INHERIT_PARENT_LIBS is ${INHERIT_PARENT_LIBS}")
	if(INHERIT_PARENT_SRC)
		set(SRC ${PARENT_SRC})
		message("'${MODULE_NAME}' project PARENT_SRC: ${PARENT_SRC}")
	endif()
endmacro(setup_inherit_parent)
